# Generated by Django 3.1.2 on 2020-10-16 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('type_of_project', models.CharField(max_length=50)),
                ('project_details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('rules', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.project')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.rules')),
            ],
        ),
    ]
